/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.io.File;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sourceCode.RSA;

/**
 *
 * @author Shania
 */
public class Hal2 extends javax.swing.JFrame {

    /**
     * Creates new form Hal2
     */
    public Hal2() {
        initComponents();
    }
    public JTextField getTxtPath() {
        return txtPath;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        untukLatar1 = new assets.UntukLatar();
        jLabel1 = new javax.swing.JLabel();
        LoadData = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        PrevKey = new javax.swing.JToggleButton();
        Sign = new javax.swing.JButton();
        NewKey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiTure");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/assets/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(222, 230, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        untukLatar1.setBackground(new java.awt.Color(220, 228, 252));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 7, 119));
        jLabel1.setText("Tanda Tangan Digital");

        LoadData.setBackground(new java.awt.Color(79, 82, 255));
        LoadData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoadData.setForeground(new java.awt.Color(220, 228, 252));
        LoadData.setText("Ambil Data");
        LoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadDataActionPerformed(evt);
            }
        });

        txtPath.setEditable(false);
        txtPath.setBackground(new java.awt.Color(231, 238, 254));
        txtPath.setForeground(new java.awt.Color(17, 7, 119));
        txtPath.setSelectionColor(new java.awt.Color(18, 8, 121));

        PrevKey.setBackground(new java.awt.Color(79, 82, 255));
        PrevKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PrevKey.setForeground(new java.awt.Color(220, 228, 252));
        PrevKey.setText("Ambil Kunci");
        PrevKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrevKeyMousePressed(evt);
            }
        });
        PrevKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevKeyActionPerformed(evt);
            }
        });

        Sign.setBackground(new java.awt.Color(79, 82, 255));
        Sign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sign.setForeground(new java.awt.Color(220, 228, 252));
        Sign.setText("Tanda Tangan");
        Sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignActionPerformed(evt);
            }
        });

        NewKey.setBackground(new java.awt.Color(79, 82, 255));
        NewKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewKey.setForeground(new java.awt.Color(220, 228, 252));
        NewKey.setText("Buat Kunci Baru");
        NewKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout untukLatar1Layout = new javax.swing.GroupLayout(untukLatar1);
        untukLatar1.setLayout(untukLatar1Layout);
        untukLatar1Layout.setHorizontalGroup(
            untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(untukLatar1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, untukLatar1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, untukLatar1Layout.createSequentialGroup()
                        .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(untukLatar1Layout.createSequentialGroup()
                                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LoadData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(untukLatar1Layout.createSequentialGroup()
                                .addComponent(NewKey)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sign)
                                    .addComponent(PrevKey, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );
        untukLatar1Layout.setVerticalGroup(
            untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(untukLatar1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoadData)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(PrevKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sign)
                    .addComponent(NewKey))
                .addGap(80, 80, 80))
        );

        jPanel1.add(untukLatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadDataActionPerformed
        JFileChooser dialog = new JFileChooser();
        dialog.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\DigSig\\hasil\\sources"));
        int result = dialog.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = dialog.getSelectedFile();
            try {
                String filePath = file.getAbsolutePath();
                txtPath.setText(filePath);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memilih file:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_LoadDataActionPerformed

    private void NewKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewKeyActionPerformed
        Halaman1_1 hal1 = new Halaman1_1();
        hal1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewKeyActionPerformed

    private void PrevKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevKeyActionPerformed
        if(PrevKey.isSelected()){
            String privateKey = Halaman1_1.KPrivat.getText();
        } else{
            JOptionPane.showMessageDialog(this, "Tombol belum diaktifkan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PrevKeyActionPerformed

    private void SignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignActionPerformed
    if (txtPath.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih file terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else if (!PrevKey.isSelected()) {
        JOptionPane.showMessageDialog(this, "Klik tombol Ambil Kunci terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else{
        try {
            RSA.getSignature();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Halaman1_1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Hal2.class.getName()).log(Level.SEVERE, null, ex);
        }
       JOptionPane.showMessageDialog(this, "Tanda Tangan Digital telah tersimpan ke dalam file", "Hasil Tanda Tangan Digital", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }
            Halaman3Lain hal3 = new Halaman3Lain();
            hal3.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_SignActionPerformed

    private void PrevKeyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevKeyMousePressed
        PrevKey.setBackground(new java.awt.Color(195,220,251));
        PrevKey.setForeground(new java.awt.Color(29,23,90));
    }//GEN-LAST:event_PrevKeyMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadData;
    private javax.swing.JButton NewKey;
    private javax.swing.JToggleButton PrevKey;
    private javax.swing.JButton Sign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtPath;
    private assets.UntukLatar untukLatar1;
    // End of variables declaration//GEN-END:variables
}
