/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

// HALAMAN TIDAK TERPAKAI

import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sourceCode.RSA;
import sourceCode.VERIFY;


/**
 *
 * @author Shania
 */
public class Halaman3Lain extends javax.swing.JFrame {

    /**
     * Creates new form Halaman4Lain
     */
    public Halaman3Lain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TakeMessage = new javax.swing.JTextField();
        TData = new javax.swing.JButton();
        TPrivate = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnVerif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DiTure");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/assets/icon.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 8, 121));
        jLabel1.setText("Verifikasi Tanda Tangan Digital");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 20, -1, -1));

        TakeMessage.setEditable(false);
        TakeMessage.setBackground(new java.awt.Color(231, 238, 254));
        TakeMessage.setForeground(new java.awt.Color(17, 7, 119));
        getContentPane().add(TakeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 85, 270, -1));

        TData.setBackground(new java.awt.Color(79, 82, 255));
        TData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TData.setForeground(new java.awt.Color(220, 228, 252));
        TData.setText("Ambil Data");
        TData.setMaximumSize(new java.awt.Dimension(85, 22));
        TData.setMinimumSize(new java.awt.Dimension(85, 22));
        TData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDataActionPerformed(evt);
            }
        });
        getContentPane().add(TData, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 85, 118, -1));

        TPrivate.setBackground(new java.awt.Color(79, 82, 255));
        TPrivate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TPrivate.setForeground(new java.awt.Color(220, 228, 252));
        TPrivate.setText("Ambil Kunci");
        TPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPrivateActionPerformed(evt);
            }
        });
        getContentPane().add(TPrivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 141, 118, -1));

        jPanel1.setBackground(new java.awt.Color(222, 230, 253));

        btnVerif.setBackground(new java.awt.Color(79, 82, 255));
        btnVerif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerif.setForeground(new java.awt.Color(220, 228, 252));
        btnVerif.setText("Verifikasi");
        btnVerif.setPreferredSize(new java.awt.Dimension(85, 22));
        btnVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(btnVerif, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(btnVerif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDataActionPerformed
        JFileChooser dialog = new JFileChooser();
        dialog.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\DigSig\\hasil\\sources"));
        int result = dialog.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = dialog.getSelectedFile();
            try {
                String filePath = file.getAbsolutePath();
                TakeMessage.setText(filePath);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memilih file:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_TDataActionPerformed

    private void btnVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifActionPerformed
        if (TakeMessage.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih file terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    } else if (!TPrivate.isSelected()) {
        JOptionPane.showMessageDialog(this, "Klik tombol Ambil Kunci terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else{
        try {
        VERIFY.main(new String[]{});

        BigInteger storedSignature = RSA.getEncryptedHash();
        BigInteger currentSignature = VERIFY.getCurrentSignature();

        if (storedSignature != null && currentSignature != null && VERIFY.compareSignature(storedSignature, currentSignature)) {
            JOptionPane.showMessageDialog(this, "Tanda Tangan Digital Sesuai", "Status Verifikasi", JOptionPane.INFORMATION_MESSAGE);
            VerifResult hal4 = new VerifResult();
            hal4.setVisible(true);
            VerifResult.Sign1.setText(RSA.encryptedHash.toString());
            VerifResult.Sign2.setText(VERIFY.currentSignature.toString());
            VerifResult.status.setText("Hasil Proses Tanda Tangan Digital Sama.\nTidak Ada Kesalahan atau Perubahan yang Terjadi.");
        } else {
            JOptionPane.showMessageDialog(this, "Tanda Tangan Digital Tidak Sesuai", "Status Verifikasi", JOptionPane.ERROR_MESSAGE);
            VerifResult hal4 = new VerifResult();
            hal4.setVisible(true);
            this.setVisible(false);
            VerifResult.Sign1.setText(RSA.encryptedHash.toString());
            VerifResult.Sign2.setText(VERIFY.currentSignature.toString());
            VerifResult.status.setText("Hasil Proses Tanda Tangan Digital Berbeda.\nKemungkinan Telah Terjadi Perubahan.");
        }
    } catch (NoSuchAlgorithmException ex) {
        Logger.getLogger(Halaman3Lain.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Halaman3Lain.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    }//GEN-LAST:event_btnVerifActionPerformed

    private void TPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPrivateActionPerformed
        TPrivate.setBackground(new java.awt.Color(195,220,251));
        TPrivate.setForeground(new java.awt.Color(29,23,90));
        if(TPrivate.isSelected()){
            String privateKey = Halaman1_1.KPrivat.getText();
        }else
            JOptionPane.showMessageDialog(this, "Tombol belum diaktifkan!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_TPrivateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman3Lain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TData;
    private javax.swing.JToggleButton TPrivate;
    public static javax.swing.JTextField TakeMessage;
    private javax.swing.JButton btnVerif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
