/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

// HALAMAN TIDAK TERPAKAI

import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sourceCode.RSA;
import sourceCode.VERIFY;


/**
 *
 * @author Shania
 */
public class Halaman3Lain extends javax.swing.JFrame {

    /**
     * Creates new form Halaman4Lain
     */
    public Halaman3Lain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        untukLatar1 = new assets.UntukLatar();
        jLabel1 = new javax.swing.JLabel();
        TData = new javax.swing.JButton();
        TakeMessage = new javax.swing.JTextField();
        TPrivate = new javax.swing.JToggleButton();
        btnVerif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiTure");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/assets/icon.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(222, 230, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        untukLatar1.setBackground(new java.awt.Color(220, 228, 252));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 8, 121));
        jLabel1.setText("Digital Signature Verification");

        TData.setBackground(new java.awt.Color(79, 82, 255));
        TData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TData.setForeground(new java.awt.Color(220, 228, 252));
        TData.setText("Load Data");
        TData.setMaximumSize(new java.awt.Dimension(85, 22));
        TData.setMinimumSize(new java.awt.Dimension(85, 22));
        TData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDataActionPerformed(evt);
            }
        });

        TakeMessage.setEditable(false);
        TakeMessage.setBackground(new java.awt.Color(231, 238, 254));
        TakeMessage.setForeground(new java.awt.Color(17, 7, 119));

        TPrivate.setBackground(new java.awt.Color(79, 82, 255));
        TPrivate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TPrivate.setForeground(new java.awt.Color(220, 228, 252));
        TPrivate.setText("Load Key");
        TPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPrivateActionPerformed(evt);
            }
        });

        btnVerif.setBackground(new java.awt.Color(79, 82, 255));
        btnVerif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerif.setForeground(new java.awt.Color(220, 228, 252));
        btnVerif.setText("Verify");
        btnVerif.setPreferredSize(new java.awt.Dimension(85, 22));
        btnVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout untukLatar1Layout = new javax.swing.GroupLayout(untukLatar1);
        untukLatar1.setLayout(untukLatar1Layout);
        untukLatar1Layout.setHorizontalGroup(
            untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(untukLatar1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, untukLatar1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, untukLatar1Layout.createSequentialGroup()
                        .addComponent(btnVerif, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, untukLatar1Layout.createSequentialGroup()
                        .addComponent(TakeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))))
        );
        untukLatar1Layout.setVerticalGroup(
            untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(untukLatar1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(untukLatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TakeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TPrivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnVerif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jPanel1.add(untukLatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDataActionPerformed
        JFileChooser dialog = new JFileChooser();
        dialog.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\DigSig\\hasil\\sources"));
        int result = dialog.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = dialog.getSelectedFile();
            try {
                String filePath = file.getAbsolutePath();
                TakeMessage.setText(filePath);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "An error occurred when selecting a file:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_TDataActionPerformed

    private void btnVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifActionPerformed
        if (TakeMessage.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Select the file first.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    } else if (!TPrivate.isSelected()) {
        JOptionPane.showMessageDialog(this, "Click the Load Key button first.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else{
        try {
        VERIFY.main(new String[]{});

        BigInteger storedSignature = RSA.getEncryptedHash();
        BigInteger currentSignature = VERIFY.getCurrentSignature();

        if (storedSignature != null && currentSignature != null && VERIFY.compareSignature(storedSignature, currentSignature)) {
            JOptionPane.showMessageDialog(this, "Matching Digital Signature", "Verification Status", JOptionPane.INFORMATION_MESSAGE);
            VerifResult hal4 = new VerifResult();
            hal4.setVisible(true);
            VerifResult.Sign1.setText(RSA.encryptedHash.toString());
            VerifResult.Sign2.setText(VERIFY.currentSignature.toString());
            VerifResult.status.setText("Same Digital Signature Process Results.\nNo Errors or Changes Occurred.");
        } else {
            JOptionPane.showMessageDialog(this, "Digital Signature does not Match", "Verification Status", JOptionPane.ERROR_MESSAGE);
            VerifResult hal4 = new VerifResult();
            hal4.setVisible(true);
            this.setVisible(false);
            VerifResult.Sign1.setText(RSA.encryptedHash.toString());
            VerifResult.Sign2.setText(VERIFY.currentSignature.toString());
            VerifResult.status.setText("Different Digital Signature Process Results.\nPossible Changes Have Occurred.");
        }
    } catch (NoSuchAlgorithmException ex) {
        Logger.getLogger(Halaman3Lain.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Halaman3Lain.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    }//GEN-LAST:event_btnVerifActionPerformed

    private void TPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPrivateActionPerformed
        TPrivate.setBackground(new java.awt.Color(195,220,251));
        TPrivate.setForeground(new java.awt.Color(29,23,90));
        if(TPrivate.isSelected()){
            String privateKey = Halaman1_1.KPrivat.getText();
        }else
            JOptionPane.showMessageDialog(this, "Button not activated!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_TPrivateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman3Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman3Lain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TData;
    private javax.swing.JToggleButton TPrivate;
    public static javax.swing.JTextField TakeMessage;
    private javax.swing.JButton btnVerif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private assets.UntukLatar untukLatar1;
    // End of variables declaration//GEN-END:variables
}
